### ISSUE TITLE
The 5th class may be missed in the timetable

### ISSUE THREAD

**Issue by BobAnkh** [Yurihou/Class_Bell#1]
In the [Line6](https://github.com/Yurihou/Class_Bell/blob/bf39d58b43f2e6414fcca82d928f51332eb0c5e5/bell.py#L6) of your `bell.py`, you might have missed the 5th class **from 17:05 to 18:40** of a school day in the timetable list.

**Comment by Yurihou** [comment]
Ahhh thanks for ur issue. Actually I have no course at that time lol.
